apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: credentials
  namespace: staging
spec:
  encryptedData:
    token: AgCN9koTqQwYJa6z9A8deQxEAUc9pMjRgXJxeIjf+JQYK0QQCPDBa6pWTwmd9RkNObkWrhTEn7kqqrXZanD1CbVhd02+tYeShkEsAlRB2q2uaYHC/uswooA7ZcPAdN2dSTA+AveVbfcrfcuuoTE0ZAI5fOmvGqhFJt+wFqG/KSPZC+y5VCEZgBBe2DvyQ8+WQZS508lq17dImgc0DRA7PnuLIaR3sLQFqST+ajPY3xi2gB45OhnpemW44I8wIvXTv+LcujuZTWCz8kx5XmJSJYSCEDkceRcnSLp57HuCML088Y96wjqFPY23Lu5XOTgRCzSt/7ZGCKL/HnTuel6BPL/Tofz5MaA9J/OriNVvcMcoSNmVjaLGHqW9Vq2+2B9ypuOLgjeOJNpRiQzZ3TxxbMogm+nNMii/A3pMMkOFr+/qFI75QDL5ehVLkwXXLxlMJhli9kedxlq4LpXsPo6eexTrEYlZuLoPwsmNQQOup4kmabfVX+e4L0u4i6Ioi7bbGuKY6S/cR2fvJl/tVLaV1TtFtb8mqiDzJTBUZvvYZ4kiaYjXZSQijYCbEE11F7WRZYqa6TnHQAAGbKuj0GD+MLlx5B66QsHc8u3Q6jyC2n2AyfZdE5Gfdg9DhZJnEeDAOgms+bUbvBYKyRlQZy6CcVZwiXz7kZ5HKTLN1lf9hohF7jEzfYpNzFZdjrknjWKT528B+PC1Ol8PPRc32g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: credentials
      namespace: staging
    type: Opaque

